[package]
name = "perq"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.0"
rand = "0.8.0"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "coeff_ring_bench"
harness = false

[[bench]]
name = "coeff_div_bench"
harness = false

[[bench]]
name = "seq_bench"
harness = false
